//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsLocalizedIntellisense.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VsLocalizedIntellisense.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   VsLocalizedIntellisense に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   危険 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enum_LogLevel_Critical {
            get {
                return ResourceManager.GetString("enum_LogLevel_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enum_LogLevel_Debug {
            get {
                return ResourceManager.GetString("enum_LogLevel_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   異常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enum_LogLevel_Error {
            get {
                return ResourceManager.GetString("enum_LogLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enum_LogLevel_Information {
            get {
                return ResourceManager.GetString("enum_LogLevel_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トレース に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enum_LogLevel_Trace {
            get {
                return ResourceManager.GetString("enum_LogLevel_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string enum_LogLevel_Warning {
            get {
                return ResourceManager.GetString("enum_LogLevel_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール処理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_InstallCommand_Header_A {
            get {
                return ResourceManager.GetString("UI_Main_InstallCommand_Header_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_InstallDirectory_Download_A {
            get {
                return ResourceManager.GetString("UI_Main_InstallDirectory_Download_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_InstallDirectory_Execute_A {
            get {
                return ResourceManager.GetString("UI_Main_InstallDirectory_Execute_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_InstallDirectory_Header_A {
            get {
                return ResourceManager.GetString("UI_Main_InstallDirectory_Header_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_InstallDirectory_SelectDirectory_A {
            get {
                return ResourceManager.GetString("UI_Main_InstallDirectory_SelectDirectory_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログレベル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_Log_List_Column_Header_Level {
            get {
                return ResourceManager.GetString("UI_Main_Log_List_Column_Header_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メッセージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_Log_List_Column_Header_Message {
            get {
                return ResourceManager.GetString("UI_Main_Log_List_Column_Header_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイムスタンプ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_Log_List_Column_Header_Timestamp {
            get {
                return ResourceManager.GetString("UI_Main_Log_List_Column_Header_Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対象ディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_TargetDirectories_A {
            get {
                return ResourceManager.GetString("UI_Main_TargetDirectories_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_TargetDirectories_List_Column_Header_Directory {
            get {
                return ResourceManager.GetString("UI_Main_TargetDirectories_List_Column_Header_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DL進捗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_TargetDirectories_List_Column_Header_DownloadProgress {
            get {
                return ResourceManager.GetString("UI_Main_TargetDirectories_List_Column_Header_DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インテリセンスバージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_TargetDirectories_List_Column_Header_IntellisenseVersion {
            get {
                return ResourceManager.GetString("UI_Main_TargetDirectories_List_Column_Header_IntellisenseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_TargetDirectories_List_Column_Header_Language {
            get {
                return ResourceManager.GetString("UI_Main_TargetDirectories_List_Column_Header_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライブラリバージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Main_TargetDirectories_List_Column_Header_LibraryVersion {
            get {
                return ResourceManager.GetString("UI_Main_TargetDirectories_List_Column_Header_LibraryVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力必須項目です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UI_Validation_Required {
            get {
                return ResourceManager.GetString("UI_Validation_Required", resourceCulture);
            }
        }
    }
}
